name: vistext-image_guided
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.7.*
  - h5py=3.7.0
  - numpy=1.17.*
  - pandas=1.2.4
  - pytorch=1.6.0
  - pyyaml=5.4.1
  - sacrebleu=2.0.0
  - scipy=1.4.1
  - sentencepiece=0.1.91
  - torchvision=0.7.0
  - torchtext=0.7.0
  - pip
  - pip:
      - transformers==4.2.1
      - tokenizers==0.9.4