name: vistext-py39
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.9
  - datasets>=2.6.1
  - evaluate>=0.3.0
  - gensim=4.3.0
  - h5py
  - nltk=3.7
  - numpy>=1.22.3
  - pandas>=1.4.2
  - pytorch
  - pyyaml>=5.4.1
  - sacrebleu>=2.0.0
  - scipy
  - sentencepiece=>0.1.96
  - tokenizers=>0.11.4
  - torchvision=>0.13.1
  - transformers<=4.24.0
  - pip
  - pip:
    - git+https://github.com/google-research/bleurt.git@cebe7e6f996b40910cfaa520a63db47807e3bf5c
    - pot==0.9.0
    - rouge_score